import js from "@eslint/js";

export default [
  {
    ignores: ["node_modules/", "_dist/", "_tools/lib/", "**/*.min.js", "**/*.meta.js"],
  },
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: "module",
      globals: {
        // Browser globals
        console: "readonly",
        window: "readonly",
        document: "readonly",
        location: "readonly",
        history: "readonly",
        navigator: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        fetch: "readonly",
        XMLHttpRequest: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        // Greasemonkey/Userscript globals
        GM: "readonly",
        GM_getValue: "readonly",
        GM_setValue: "readonly",
        GM_deleteValue: "readonly",
        GM_listValues: "readonly",
        GM_addValueChangeListener: "readonly",
        GM_removeValueChangeListener: "readonly",
        GM_addElement: "readonly",
        GM_addScript: "readonly",
        GM_addStyle: "readonly",
        GM_download: "readonly",
        GM_getResourceText: "readonly",
        GM_getResourceURL: "readonly",
        GM_info: "readonly",
        GM_log: "readonly",
        GM_notification: "readonly",
        GM_openInTab: "readonly",
        GM_popup: "readonly",
        GM_registerMenuCommand: "readonly",
        GM_unregisterMenuCommand: "readonly",
        GM_setClipboard: "readonly",
        GM_fetch: "readonly",
        GM_xmlhttpRequest: "readonly",
        unsafeWindow: "readonly",
        exportFunction: "readonly",
        cloneInto: "readonly",
        // Safari Userscripts
        safari: "readonly",
      },
    },
    rules: {
      ...js.configs.recommended.rules,
      curly: ["error", "all"],
      eqeqeq: ["error", "always"],
      "no-caller": "error",
      "no-new-wrappers": "error",
      "no-undef": "error",
      "no-unused-vars": [
        "warn",
        {
          args: "after-used",
          argsIgnorePattern: "^_",
        },
      ],
      "no-var": "error",
      "prefer-const": "warn",
      "prefer-arrow-callback": "warn",
      "no-console": "off",
      "valid-typeof": ["error", { requireStringLiterals: true }],
      "no-implicit-coercion": "warn",
      "no-with": "error",
      "no-eval": "error",
    },
  },
];
